Leos\Domain\User\Model\User:
    type: entity
    table: user
    repositoryClass: Leos\Infrastructure\UserBundle\Repository\UserRepository
    id:
      uuid:
        type: userId
        nullable: false
    indexes:
      email_index:
        columns: [ email ]

    uniqueConstraints:
        search_idx:
          columns: [ auth_username ]

    fields:
      email:
        type: string
        unique: true
        length: 32
        nullable: false

      createdAt:
        type: datetime

      updatedAt:
        type: datetime
        nullable: true

    embedded:
      auth:
        class: Leos\Domain\Security\ValueObject\AuthUser

    lifecycleCallbacks: {  }
