# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: '5.7'

        types:
            walletId: Leos\Infrastructure\WalletBundle\Doctrine\Types\WalletIdType
            transactionId: Leos\Infrastructure\TransactionBundle\Doctrine\Types\TransactionIdType
            userId: Leos\Infrastructure\UserBundle\Doctrine\Types\UserIdType
            eventAwareId: Leos\Infrastructure\CommonBundle\Doctrine\Types\EventAwareIdType

        mapping_types:
            json: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:

            Transaction:
                type: yml
                prefix: Leos\Domain\Transaction\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/TransactionBundle/Resources/config/persistence/Model'
                is_bundle: false

            TransactionValueObject:
                type: yml
                prefix: Leos\Domain\Transaction\ValueObject
                dir: '%kernel.root_dir%/../src/Infrastructure/TransactionBundle/Resources/config/persistence/ValueObject'
                is_bundle: false

            Payment:
                type: yml
                prefix: Leos\Domain\Payment\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/PaymentBundle/Resources/config/persistence/Model'
                is_bundle: false


            WalletFactory:
                type: yml
                prefix: Leos\Domain\Wallet\Factory
                dir: '%kernel.root_dir%/../src/Infrastructure/WalletBundle/Resources/config/persistence/Factory'
                is_bundle: false

            Wallet:
                type: yml
                prefix: Leos\Domain\Wallet\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/WalletBundle/Resources/config/persistence/Model'
                is_bundle: false

            Money:
                type: yml
                prefix: Leos\Domain\Money\ValueObject
                dir: '%kernel.root_dir%/../src/Infrastructure/MoneyBundle/Resources/config/persistence/ValueObject'
                is_bundle: false

            WalletValueObject:
                type: yml
                prefix: Leos\Domain\Wallet\ValueObject
                dir: '%kernel.root_dir%/../src/Infrastructure/WalletBundle/Resources/config/persistence/ValueObject'
                is_bundle: false

            User:
                type: yml
                prefix: Leos\Domain\User\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/UserBundle/Resources/config/persistence/Model'
                is_bundle: false

            Security:
                type: yml
                prefix: Leos\Domain\Security\ValueObject
                dir: '%kernel.root_dir%/../src/Infrastructure/SecurityBundle/Resources/config/persistence/ValueObject'
                is_bundle: false

            Common:
                type: yml
                prefix: Leos\Infrastructure\CommonBundle\Event
                dir: '%kernel.root_dir%/../src/Infrastructure/CommonBundle/Resources/config/persistence'
                is_bundle: false
