Leos\Domain\Wallet\Model\Wallet:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\WalletId

        real:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        bonus:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        createdAt:
            expose: true
            groups: [Basic]

        updatedAt:
            expose: true
            groups: [Basic]
