Leos\Domain\Transaction\Model\AbstractTransaction:
    exclusion_policy: ALL
    discriminator:
      field_name: discriminator
      map:
        deposit: Leos\Domain\Payment\Model\Deposit
        rollback_deposit: Leos\Domain\Payment\Model\RollbackDeposit
        withdrawal: Leos\Domain\Payment\Model\Withdrawal
        rollback_withdrawal: Leos\Domain\Payment\Model\RollbackWithdrawal
        create_wallet: Leos\Domain\Wallet\Factory\WalletFactory

    properties:
        type:
            expose: true
            groups: [Basic]
            inline: true
            type: Leos\Domain\Transaction\ValueObject\TransactionType

        operationReal:
            expose: true
            groups: [Basic]

        operationBonus:
            expose: true
            groups: [Basic]

        prevReal:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        prevBonus:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Wallet\ValueObject\Credit

        createdAt:
            expose: true
            groups: [Basic]

        updatedAt:
            expose: true
            groups: [Basic]

        wallet:
            expose: true
            groups: [Identifier, Basic]
            type: Leos\Domain\Wallet\Model\Wallet

        details:
            expose: true
            groups: [Basic]

        referralTransaction:
            expose: true
            groups: [Basic]
            type: Leos\Domain\Transaction\Model\AbstractTransaction
